- name: play1
  hosts: all
  become: yes # elevates privilege to root
  tasks:
    - name: Demo for shell
      ansible.builtin.shell: id
      register: OUT  #stores output of shell command and preserves it in the variable of our choice

    - name: Printing hello from task1 of play2
      ansible.builtin.debug:
          msg: printing {{OUT.stdout}}