
- name: Calling Nodejs function
  include_role:
    name: common
    tasks_from: nodejs


# - name: Configuring NodeJS repo
#   ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

# - name: Install NodeJS
#   ansible.builtin.package:
#     name: nodejs
#     state: present

# - name: Add the user {{APPUSER}}
#   ansible.builtin.user:
#     name: "{{APPUSER}}"
#     comment: roboshop service account user
    

# - name: Download and Extract {{component}}
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
#     dest: /tmp
#     remote_src: yes

# - name: Recursively remove Old Contents
#   ansible.builtin.file:
#     path: /home/{{APPUSER}}/{{component}}/
#     state: absent

# - name: Copy file to roboshop home directory
#   ansible.builtin.copy:
#     src: /tmp/{{component}}-main/
#     dest: /home/{{APPUSER}}/{{component}}/
#     remote_src: yes
#     owner: "{{APPUSER}}"
#     group: "{{APPUSER}}"

# - name: Install node.js package.
#   community.general.npm:
#     name: coffee-script
#     path: /home/{{APPUSER}}/{{component}}/

# # - name: Update systemd.service
# #   ansible.builtin.replace:
# #     path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
# #     regexp: 'MONGO_DNSNAME'
# #     replace: 'mongodb-dev.roboshop.internal'
    
# - name: Copy systemd.service file to systemd folder
#   ansible.builtin.template:
#     src: systemd.service
#     dest: /etc/systemd/system/{{COMPONENT}}.service
#     owner: root
#     group: root

# - name: Just force systemd to reread configs and restart
#   ansible.builtin.systemd:
#     state: started
#     name: "{{COMPONENT}}"
#     enabled: yes
#     daemon_reload: yes

# # - name: Just force systemd to reread configs
# #   ansible.builtin.systemd:
# #     daemon_reload: yes

# # - name: Enable and restart
# #   ansible.builtin.systemd:
# #     name: "{{COMPONENT}}"
# #     state: started
# #     enabled: yes
