- name: Download and Extract {{component}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  ignore_errors: yes

- name: Recursively remove Old Contents
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{component}}/
    state: absent
  ignore_errors: yes

- name: Copy file to roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{component}}-main/
    dest: /home/{{APPUSER}}/{{component}}/
    remote_src: yes
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
  ignore_errors: yes