- name: Configuring NodeJS repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NodeJS
  ansible.builtin.package:
    name: nodejs
    state: present


- name: Calling roboshop create-user function
  include_role:
    name: common
    tasks_from: create-user
# - name: Add the user {{APPUSER}}
#   ansible.builtin.user:
#     name: "{{APPUSER}}"
#     comment: roboshop service account user
    
- name: Calling download function
  include_role:
    name: common
    tasks_from: download-nexus
# - name: Download and Extract {{COMPONENT}}
#   ansible.builtin.unarchive:
#     src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
#     dest: /tmp
#     remote_src: yes

# - name: Recursively remove Old Contents
#   ansible.builtin.file:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/
#     state: absent

# - name: Copy file to roboshop home directory
#   ansible.builtin.copy:
#     src: /tmp/{{COMPONENT}}-main/
#     dest: /home/{{APPUSER}}/{{COMPONENT}}/
#     remote_src: yes
#     owner: "{{APPUSER}}"
#     group: "{{APPUSER}}"

# - name: Install node.js package.
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{component}}/

# - name: Update systemd.service
#   ansible.builtin.replace:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
#     regexp: 'MONGO_DNSNAME'
#     replace: 'mongodb-dev.roboshop.internal'
- name: Calling config service function
  include_role:
    name: common
    tasks_from: config-svc   
# - name: Copy systemd.service file to systemd folder
#   ansible.builtin.template:
#     src: systemd.service
#     dest: /etc/systemd/system/{{COMPONENT}}.service
#     owner: root
#     group: root

# - name: Just force systemd to reread configs and restart
#   ansible.builtin.systemd:
#     state: started
#     name: "{{COMPONENT}}"
#     enabled: yes
#     daemon_reload: yes

- name: Set Hostname
  ansible.builtin.shell: set-hostname {{component}}